### ISSUE TITLE
Error running the README example

### ISSUE THREAD

**Issue by coderade** [kamicane/simple-ftpd#6] opened 2018-02-16 20:09 UTC
### My Machine

- OS Version: Manjaro Linux 17.1.4
- Node: v9.0.0

### Steps to Reproduce:
Run the [example](https://github.com/kamicane/simple-ftpd#example) on the README directly with the `node` command on the command line (eg. `node ftp.js` )

I think that is something related with my Node.js version.

#### Error

```
util.js:976
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'superCtor', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "superCtor" argument must be of type function
    at Object.inherits (util.js:976:11)
    at Object.<anonymous> (/home/coderade/repo/tests/ftp-server-example/node_modules/ftpd/lib/ftpd.js:67:6)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/coderade/repo/tests/ftp-server-example/ftp.js:3:14)
```
Do you know why this can be happening? Need help to solve this issue?

**Comment by Matheus-Garbelini** [comment] 2018-02-27 11:14
@coderade do you got it working? same problem here

**Comment by benfavre** [comment] 2018-06-21 15:00
Readme is wrong, you should install "simple-ftpd"
```
npm install simple-ftpd --save

**Comment by Matheus-Garbelini** [comment] 2018-07-13 02:16
@benfavre seriously? oooh my ggggóóóód

**Comment by coderade** [comment] 2018-07-13 02:27
Hi @Matheus-Garbelini, no, the module didn't worked. I used the [jsftp](https://github.com/sergi/jsftp) on my project.

**Comment by kamicane** [comment] 2018-07-21 10:15
second part is a duplicate of #8.
fixed the typos in the README.

**Closed as completed by kamicane** 2018-07-21 10:15 UTC
