### ISSUE TITLE
Cannot find module 'ftpd'

### ISSUE THREAD

**Issue by BugKiller-tech** [kamicane/simple-ftpd#9] opened 2018-06-15 19:45 UTC
I've installed simple-ftpd but I got the following error.

> `const ftpd = require('ftpd');`

This code gives me error like below.

```
Error: Cannot find module 'ftpd'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Work/Work/WEB/nodejs/simple-ftpd-test/server.js:2:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I tried to this code.

> `const ftpd = require('simple-ftpd');`

then I'm getting error like this.

```
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/Work/Work/WEB/nodejs/simple-ftpd-test/node_modules/simple-ftpd/lib/session.js:8:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by kamicane** [comment] 2018-07-21 10:15
duplicate of #8

**Closed as completed by kamicane** 2018-07-21 10:15 UTC
